package com.yoesuv.mynote.controller

object TestConstants {
    const val BASE_URL_NOTES = "/api/notes"
    const val BASE_URL_CATEGORIES = "/api/categories"
    const val AUTH_URL = "/api/auth/register"
    const val TEST_EMAIL = "test@example.com"
    const val TEST_PASSWORD = "password123"
    const val TEST_FULL_NAME = "Test User"

    const val KEY_TITLE = "title"
    const val KEY_CONTENT = "content"
    const val KEY_IS_PINNED = "isPinned"
    const val KEY_CATEGORY_ID = "categoryId"
    const val KEY_NAME = "name"
    const val KEY_COLOR = "color"
    const val KEY_EMAIL = "email"
    const val KEY_PASSWORD = "password"
    const val KEY_FULL_NAME = "fullName"

    const val JSON_PATH_ROOT = "$"
    const val JSON_PATH_ID =JSON_PATH_ROOT + ".id"
    const val JSON_PATH_TITLE = JSON_PATH_ROOT + ".title"
    const val JSON_PATH_CONTENT = JSON_PATH_ROOT + ".content"
    const val JSON_PATH_IS_PINNED = JSON_PATH_ROOT + ".isPinned"
    const val JSON_PATH_USER_ID = JSON_PATH_ROOT + ".userId"
    const val JSON_PATH_MESSAGE = JSON_PATH_ROOT + ".message"
    const val JSON_PATH_ERROR = JSON_PATH_ROOT + ".error"
    const val JSON_PATH_ERRORS_TITLE = JSON_PATH_ROOT + ".errors.title"
    const val JSON_PATH_CATEGORY_ID = JSON_PATH_ROOT + ".category.id"
    const val JSON_PATH_CATEGORY_NAME = JSON_PATH_ROOT + ".category.name"
    const val JSON_PATH_FIRST_TITLE = JSON_PATH_ROOT + "[0].title"
    const val JSON_PATH_SECOND_TITLE = JSON_PATH_ROOT + "[1].title"
    const val JSON_PATH_FIRST_CATEGORY_ID = JSON_PATH_ROOT + "[0].category.id"

    const val NOTE_TEST_TITLE = "Test Note"
    const val NOTE_TEST_CONTENT = "Test Content"
    const val NOTE_1_TITLE = "Note 1"
    const val NOTE_2_TITLE = "Note 2"
    const val NOTE_1_CONTENT = "Content 1"
    const val NOTE_2_CONTENT = "Content 2"
    const val NOTE_UPDATED_TITLE = "Updated Title"
    const val NOTE_UPDATED_CONTENT = "Updated Content"
    const val NOTE_ORIGINAL_TITLE = "Original Title"
    const val NOTE_ORIGINAL_CONTENT = "Original Content"
    const val NOTE_PINNED_TITLE = "Pinned Note"
    const val NOTE_WITHOUT_CATEGORY = "Note without category"
    const val NOTE_WITH_CATEGORY = "Note with category"
    const val CATEGORY_WORK = "Work"
    const val COLOR_RED = "#FF0000"

    const val HEADER_AUTHORIZATION = "Authorization"
    const val BEARER_PREFIX = "Bearer "

    const val NOTE_NOT_FOUND_MSG = "Note not found with id:"
    const val CATEGORY_NOT_FOUND_MSG = "Category not found with id:"
    const val TITLE_REQUIRED_MSG = "Title is required"
    const val TITLE_LENGTH_MSG = "Title must be between 1 and 200 characters"
    const val INVALID_JSON_MSG = "Invalid JSON format"
    const val NOTE_DELETED_MSG = "Note deleted successfully"
}