-- PostgreSQL database dump

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- Name: users; Type: TABLE

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

-- Name: users_id_seq; Type: SEQUENCE

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: categories; Type: TABLE

CREATE TABLE public.categories (
    id bigint NOT NULL,
    color character varying(7),
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);

-- Name: categories_id_seq; Type: SEQUENCE

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: notes; Type: TABLE

CREATE TABLE public.notes (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    is_pinned boolean NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category_id bigint,
    user_id bigint NOT NULL
);

-- Name: notes_id_seq; Type: SEQUENCE

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: users users_pkey; Type: CONSTRAINT

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- Name: categories categories_pkey; Type: CONSTRAINT

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

-- Name: notes notes_pkey; Type: CONSTRAINT

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);

-- Name: categories fkghuylkwuedgl2qahxjt8g41kb; Type: FK CONSTRAINT

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fkghuylkwuedgl2qahxjt8g41kb FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: notes fkechaouoa6kus6k1dpix1u91c; Type: FK CONSTRAINT

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fkechaouoa6kus6k1dpix1u91c FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Name: notes fkt8k9l9q6louhlu7udo6r6l1et; Type: FK CONSTRAINT

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fkt8k9l9q6louhlu7udo6r6l1et FOREIGN KEY (category_id) REFERENCES public.categories(id);

-- PostgreSQL database dump complete