-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS dbo;

-- Create users table
CREATE TABLE IF NOT EXISTS dbo.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    full_name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

-- Create categories table
CREATE TABLE IF NOT EXISTS dbo.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color character varying(7),
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);

-- Create notes table
CREATE TABLE IF NOT EXISTS dbo.notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    is_pinned boolean NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category_id bigint,
    user_id bigint NOT NULL
);

-- Add foreign key constraints
ALTER TABLE dbo.categories 
    ADD CONSTRAINT fk_categories_user 
    FOREIGN KEY (user_id) REFERENCES dbo.users(id);

ALTER TABLE dbo.notes 
    ADD CONSTRAINT fk_notes_user 
    FOREIGN KEY (user_id) REFERENCES dbo.users(id);

ALTER TABLE dbo.notes 
    ADD CONSTRAINT fk_notes_category 
    FOREIGN KEY (category_id) REFERENCES dbo.categories(id);
